# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDK_Tencent_Bugly' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SDK_Tencent_Bugly
  pod 'Bugly'
end
