# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RC_IMDEmo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RC_IMDEmo
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
end
